/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JLabel;
import javax.swing.JTextField;
import static calculador.ProgramaPrincipal.calcula;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Restas extends javax.swing.JFrame {

    /**
     * Creates new form Sumas
     */
    private JLabel etiquetas[];
    private JTextField textos[];
    private boolean botonPulsado;
    private Calendar tiempoInicial;
    private Calendar tiempoFinal;
    private double tiempo;
    private JLabel aciertos[];
    private JLabel fallos[];

    public Restas() {
        initComponents();
        botonPulsado = false;
        tiempo = 0;
        record.setText("" + calcula.getLibro().getRecordRestas());
        this.etiquetas = new JLabel[40];
        this.textos = new JTextField[20];
        this.aciertos = new JLabel[20];
        this.fallos = new JLabel[20];
        this.etiquetas[0] = j1;
        this.etiquetas[1] = j2;
        this.etiquetas[2] = j3;
        this.etiquetas[3] = j4;
        this.etiquetas[4] = j5;
        this.etiquetas[5] = j6;
        this.etiquetas[6] = j7;
        this.etiquetas[7] = j8;
        this.etiquetas[8] = j9;
        this.etiquetas[9] = j10;
        this.etiquetas[10] = j11;
        this.etiquetas[11] = j12;
        this.etiquetas[12] = j13;
        this.etiquetas[13] = j14;
        this.etiquetas[14] = j15;
        this.etiquetas[15] = j16;
        this.etiquetas[16] = j17;
        this.etiquetas[17] = j18;
        this.etiquetas[18] = j19;
        this.etiquetas[19] = j20;
        this.etiquetas[20] = j21;
        this.etiquetas[21] = j22;
        this.etiquetas[22] = j23;
        this.etiquetas[23] = j24;
        this.etiquetas[24] = j25;
        this.etiquetas[25] = j26;
        this.etiquetas[26] = j27;
        this.etiquetas[27] = j28;
        this.etiquetas[28] = j29;
        this.etiquetas[29] = j30;
        this.etiquetas[30] = j31;
        this.etiquetas[31] = j32;
        this.etiquetas[32] = j33;
        this.etiquetas[33] = j34;
        this.etiquetas[34] = j35;
        this.etiquetas[35] = j36;
        this.etiquetas[36] = j37;
        this.etiquetas[37] = j38;
        this.etiquetas[38] = j39;
        this.etiquetas[39] = j40;
        this.textos[0] = t1;
        this.textos[1] = t2;
        this.textos[2] = t3;
        this.textos[3] = t4;
        this.textos[4] = t5;
        this.textos[5] = t6;
        this.textos[6] = t7;
        this.textos[7] = t8;
        this.textos[8] = t9;
        this.textos[9] = t10;
        this.textos[10] = t11;
        this.textos[11] = t12;
        this.textos[12] = t13;
        this.textos[13] = t14;
        this.textos[14] = t15;
        this.textos[15] = t16;
        this.textos[16] = t17;
        this.textos[17] = t18;
        this.textos[18] = t19;
        this.textos[19] = t20;
        this.aciertos[0] = a1;
        this.aciertos[1] = a2;
        this.aciertos[2] = a3;
        this.aciertos[3] = a4;
        this.aciertos[4] = a5;
        this.aciertos[5] = a6;
        this.aciertos[6] = a7;
        this.aciertos[7] = a8;
        this.aciertos[8] = a9;
        this.aciertos[9] = a10;
        this.aciertos[10] = a11;
        this.aciertos[11] = a12;
        this.aciertos[12] = a13;
        this.aciertos[13] = a14;
        this.aciertos[14] = a15;
        this.aciertos[15] = a16;
        this.aciertos[16] = a17;
        this.aciertos[17] = a18;
        this.aciertos[18] = a19;
        this.aciertos[19] = a20;
        this.fallos[0] = f1;
        this.fallos[1] = f2;
        this.fallos[2] = f3;
        this.fallos[3] = f4;
        this.fallos[4] = f5;
        this.fallos[5] = f6;
        this.fallos[6] = f7;
        this.fallos[7] = f8;
        this.fallos[8] = f9;
        this.fallos[9] = f10;
        this.fallos[10] = f11;
        this.fallos[11] = f12;
        this.fallos[12] = f13;
        this.fallos[13] = f14;
        this.fallos[14] = f15;
        this.fallos[15] = f16;
        this.fallos[16] = f17;
        this.fallos[17] = f18;
        this.fallos[18] = f19;
        this.fallos[19] = f20;
        for (int i = 0; i < 20; i++) {
            textos[i].setEditable(false);
            aciertos[i].setVisible(false);
            fallos[i].setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cotaInferior = new javax.swing.JTextField();
        cotaSuperior = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        record = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        a3 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        j15 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        j16 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        j12 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        j18 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        j14 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        j13 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        f8 = new javax.swing.JLabel();
        j17 = new javax.swing.JLabel();
        f9 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        j25 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        f12 = new javax.swing.JLabel();
        j26 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        j22 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        j28 = new javax.swing.JLabel();
        j21 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        j24 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        j23 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        j27 = new javax.swing.JLabel();
        f14 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        a13 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        j35 = new javax.swing.JLabel();
        f16 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        f17 = new javax.swing.JLabel();
        j36 = new javax.swing.JLabel();
        t16 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        a16 = new javax.swing.JLabel();
        j32 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        j38 = new javax.swing.JLabel();
        j31 = new javax.swing.JLabel();
        a19 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        j34 = new javax.swing.JLabel();
        a17 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        j33 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        t19 = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        f18 = new javax.swing.JLabel();
        j37 = new javax.swing.JLabel();
        f19 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        a18 = new javax.swing.JLabel();
        t18 = new javax.swing.JTextField();
        f5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        a5 = new javax.swing.JLabel();
        j10 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        f10 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        a10 = new javax.swing.JLabel();
        j20 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        j19 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        f15 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        a15 = new javax.swing.JLabel();
        j30 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        j29 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        f20 = new javax.swing.JLabel();
        t20 = new javax.swing.JTextField();
        a20 = new javax.swing.JLabel();
        j40 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        j39 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setText("Cota inferior  :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setText("Cota superior :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 10)); // NOI18N
        jLabel3.setText("*Introduce el intervalo en el que se generarán los números*");

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel4.setText("Record :");

        record.setFont(new java.awt.Font("Perpetua Titling MT", 3, 36)); // NOI18N
        record.setText("92,7");

        j1.setText("2");

        jLabel7.setText("-");

        j2.setText("3");

        jLabel9.setText("=");

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j4.setText("3");

        jLabel15.setText("=");

        j3.setText("2");

        jLabel17.setText("-");

        jLabel18.setText("=");

        f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j7.setText("2");

        f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel22.setText("-");

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j6.setText("3");

        jLabel25.setText("=");

        j5.setText("2");

        jLabel27.setText("-");

        j8.setText("3");

        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j15.setText("0");

        f6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel32.setText("-");

        f7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j16.setText("5");

        jLabel35.setText("=");

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j12.setText("5");

        jLabel38.setText("=");

        j18.setText("5");

        j11.setText("0");

        a9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel42.setText("-");

        j14.setText("5");

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel45.setText("=");

        j13.setText("0");

        jLabel47.setText("-");

        jLabel48.setText("=");

        f8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j17.setText("0");

        f9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel52.setText("-");

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j25.setText("2");

        f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel56.setText("-");

        f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j26.setText("0");

        jLabel59.setText("=");

        a11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j22.setText("0");

        jLabel62.setText("=");

        j28.setText("0");

        j21.setText("2");

        a14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel66.setText("-");

        j24.setText("0");

        a12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel69.setText("=");

        j23.setText("2");

        jLabel71.setText("-");

        jLabel72.setText("=");

        f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j27.setText("2");

        f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel76.setText("-");

        a13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j35.setText("1");

        f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel80.setText("-");

        f17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j36.setText("5");

        jLabel83.setText("=");

        a16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j32.setText("5");

        jLabel86.setText("=");

        j38.setText("5");

        j31.setText("1");

        a19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel90.setText("-");

        j34.setText("5");

        a17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        jLabel93.setText("=");

        j33.setText("1");

        jLabel95.setText("-");

        jLabel96.setText("=");

        f18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        j37.setText("1");

        f19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        jLabel100.setText("-");

        a18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j10.setText("3");

        jLabel105.setText("=");

        j9.setText("2");

        jLabel107.setText("-");

        f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        a10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j20.setText("5");

        jLabel111.setText("=");

        j19.setText("0");

        jLabel113.setText("-");

        f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        a15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j30.setText("0");

        jLabel117.setText("=");

        j29.setText("2");

        jLabel119.setText("-");

        f20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/fallo.png"))); // NOI18N

        a20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/acierto.png"))); // NOI18N

        j40.setText("5");

        jLabel123.setText("=");

        j39.setText("1");

        jLabel125.setText("-");
        jLabel125.setToolTipText("");

        boton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        boton.setText("Empezar reto");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculador/back.jpeg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cotaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel76)
                                            .addGap(18, 18, 18)
                                            .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel72)
                                            .addGap(18, 18, 18)
                                            .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(a14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f14))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel56)
                                            .addGap(18, 18, 18)
                                            .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel59)
                                            .addGap(18, 18, 18)
                                            .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(a13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f13))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel71)
                                            .addGap(18, 18, 18)
                                            .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel69)
                                            .addGap(18, 18, 18)
                                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(a12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f12))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel66)
                                            .addGap(18, 18, 18)
                                            .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel62)
                                            .addGap(18, 18, 18)
                                            .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(a11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(f11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel119)
                                        .addGap(18, 18, 18)
                                        .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel117)
                                        .addGap(18, 18, 18)
                                        .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f15))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cotaInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(70, 70, 70)
                        .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel107)
                        .addGap(18, 18, 18)
                        .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel105)
                        .addGap(18, 18, 18)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f1)))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel113)
                        .addGap(18, 18, 18)
                        .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel111)
                        .addGap(18, 18, 18)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addGap(18, 18, 18)
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel100)
                        .addGap(18, 18, 18)
                        .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel96)
                        .addGap(18, 18, 18)
                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel80)
                        .addGap(18, 18, 18)
                        .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel83)
                        .addGap(18, 18, 18)
                        .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel95)
                        .addGap(18, 18, 18)
                        .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel93)
                        .addGap(18, 18, 18)
                        .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel90)
                        .addGap(18, 18, 18)
                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel86)
                        .addGap(18, 18, 18)
                        .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel125)
                        .addGap(18, 18, 18)
                        .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel123)
                        .addGap(18, 18, 18)
                        .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f20)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cotaInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(record))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cotaSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j1)
                                .addComponent(jLabel7)
                                .addComponent(j2)
                                .addComponent(jLabel9)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a1)
                            .addComponent(f1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j3)
                                .addComponent(jLabel17)
                                .addComponent(j4)
                                .addComponent(jLabel15)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a2)
                            .addComponent(f2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j5)
                                .addComponent(jLabel27)
                                .addComponent(j6)
                                .addComponent(jLabel25)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a3)
                            .addComponent(f3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j7)
                                .addComponent(jLabel22)
                                .addComponent(j8)
                                .addComponent(jLabel18)
                                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a4)
                            .addComponent(f4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j11)
                                .addComponent(jLabel42)
                                .addComponent(j12)
                                .addComponent(jLabel38)
                                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a6)
                            .addComponent(f6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j13)
                                .addComponent(jLabel47)
                                .addComponent(j14)
                                .addComponent(jLabel45)
                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a7)
                            .addComponent(f7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j15)
                                .addComponent(jLabel32)
                                .addComponent(j16)
                                .addComponent(jLabel35)
                                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a8)
                            .addComponent(f8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j17)
                                .addComponent(jLabel52)
                                .addComponent(j18)
                                .addComponent(jLabel48)
                                .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a9)
                            .addComponent(f9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j21)
                                .addComponent(jLabel66)
                                .addComponent(j22)
                                .addComponent(jLabel62)
                                .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a11)
                            .addComponent(f11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j23)
                                .addComponent(jLabel71)
                                .addComponent(j24)
                                .addComponent(jLabel69)
                                .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a12)
                            .addComponent(f12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j25)
                                .addComponent(jLabel56)
                                .addComponent(j26)
                                .addComponent(jLabel59)
                                .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a13)
                            .addComponent(f13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j27)
                                .addComponent(jLabel76)
                                .addComponent(j28)
                                .addComponent(jLabel72)
                                .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a14)
                            .addComponent(f14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j31)
                                .addComponent(jLabel90)
                                .addComponent(j32)
                                .addComponent(jLabel86)
                                .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a16)
                            .addComponent(f16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j33)
                                .addComponent(jLabel95)
                                .addComponent(j34)
                                .addComponent(jLabel93)
                                .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a17)
                            .addComponent(f17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j35)
                                .addComponent(jLabel80)
                                .addComponent(j36)
                                .addComponent(jLabel83)
                                .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a18)
                            .addComponent(f18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j37)
                                .addComponent(jLabel100)
                                .addComponent(j38)
                                .addComponent(jLabel96)
                                .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a19)
                            .addComponent(f19))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j9)
                        .addComponent(jLabel107)
                        .addComponent(j10)
                        .addComponent(jLabel105)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a5)
                    .addComponent(f5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j19)
                        .addComponent(jLabel113)
                        .addComponent(j20)
                        .addComponent(jLabel111)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a10)
                    .addComponent(f10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j29)
                        .addComponent(jLabel119)
                        .addComponent(j30)
                        .addComponent(jLabel117)
                        .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a15)
                    .addComponent(f15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j39)
                        .addComponent(jLabel125)
                        .addComponent(j40)
                        .addComponent(jLabel123)
                        .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(a20)
                    .addComponent(f20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
        if (!botonPulsado) {
            try {

                int cotaInf = Integer.parseInt(cotaInferior.getText());
                int cotaSup = Integer.parseInt(cotaSuperior.getText());
                //System.out.println("Bien 1");
                //Comprobamos que el usuario haya introducido correctamente ambas cotas
                if (cotaInf < cotaSup) {
                    //Generamos los numeros para rellenar las etiquetas
                    for (int i = 0; i < 40; i++) {
                        int numeroGenerado = calcula.generadorNumeroAleatorio(cotaSup, cotaInf);
                        calcula.getNumerosGenerados()[i] = numeroGenerado;
                        etiquetas[i].setText("" + numeroGenerado);
                    }
                    //Habilitamos las respuestas
                    for (int i = 0; i < 20; i++) {
                        textos[i].setEditable(true);
                        textos[i].setText("");
                    }
                    //Escribimos en el boton donde habra que pinchar al terminar
                    boton.setText("Terminar reto");
                    //Iniciamos el tiempo
                    tiempoInicial = Calendar.getInstance();
                    tiempo = tiempoInicial.getTimeInMillis();
                    botonPulsado = true;
                    for (int i = 0; i < 20; i++) {
                        aciertos[i].setVisible(false);
                        fallos[i].setVisible(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al introducir las cotas , la cota inferior debe ser menor que la superior.", "Error", JOptionPane.WARNING_MESSAGE);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al introducir las cotas", "Error", JOptionPane.WARNING_MESSAGE);

            }
        } else {
            //Marcamos el tiempo se ha tardado en realizar el reto
            tiempoFinal = Calendar.getInstance();
            tiempo = (tiempoFinal.getTimeInMillis() - tiempo) / 1000;
            //Comprobamos si el usuario ha realizado bien las operaciones
            try {
                //Contador para los sumandos
                int j = 0;
                for (int i = 0; i < 20; i++) {
                    int operandoUno = calcula.getNumerosGenerados()[j];
                    int operandoDos = calcula.getNumerosGenerados()[j + 1];
                    textos[i].setEditable(false);
                    //Aumentamos el contador para obtener los siguientes dos sumandos de la operacion
                    j = j + 2;
                    if (calcula.comprobarRestaAcertada(operandoUno, operandoDos, Integer.parseInt(textos[i].getText()))) {
                        aciertos[i].setVisible(true);
                    } else {
                        fallos[i].setVisible(true);
                    }
                }
                JOptionPane.showMessageDialog(this, "Has respondido " + calcula.getRestasAcertadas() + " operaciones correctamente en " + tiempo + " segundos", "Resultado", JOptionPane.WARNING_MESSAGE);
                //En caso de acertar todas las operaciones , comprobamos si se ha batido el record
                if (calcula.getRestasAcertadas() == 20) {
                    calcula.comprobarRecordResta(tiempo);
                    record.setText("" + calcula.getLibro().getRecordRestas());
                    JOptionPane.showMessageDialog(this, "Enhorabuena , has destrozado tu ultima marca personal.", "Enhorabuena", JOptionPane.WARNING_MESSAGE);

                }
                //Reiniciamos los valores 
                calcula.setRestasAcertadas(0);
                for (int i = 0; i < 20; i++) {
                    textos[i].setEditable(false);
                }
                boton.setText("Comenzar reto");
                botonPulsado = false;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al introducir algunas de las respuetas , el reto ha sido cancelado.", "Error", JOptionPane.WARNING_MESSAGE);
                //Reiniciamos los valores 
                calcula.setRestasAcertadas(0);
                for (int i = 0; i < 20; i++) {
                    textos[i].setEditable(false);
                }
                boton.setText("Comenzar reto");
                botonPulsado = false;
            }
        }
    }//GEN-LAST:event_botonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal vistaPrincipal = new Principal();
        vistaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a13;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel a16;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a18;
    private javax.swing.JLabel a19;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a20;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JButton boton;
    private javax.swing.JTextField cotaInferior;
    private javax.swing.JTextField cotaSuperior;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JLabel f14;
    private javax.swing.JLabel f15;
    private javax.swing.JLabel f16;
    private javax.swing.JLabel f17;
    private javax.swing.JLabel f18;
    private javax.swing.JLabel f19;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f20;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel f9;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j13;
    private javax.swing.JLabel j14;
    private javax.swing.JLabel j15;
    private javax.swing.JLabel j16;
    private javax.swing.JLabel j17;
    private javax.swing.JLabel j18;
    private javax.swing.JLabel j19;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j20;
    private javax.swing.JLabel j21;
    private javax.swing.JLabel j22;
    private javax.swing.JLabel j23;
    private javax.swing.JLabel j24;
    private javax.swing.JLabel j25;
    private javax.swing.JLabel j26;
    private javax.swing.JLabel j27;
    private javax.swing.JLabel j28;
    private javax.swing.JLabel j29;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j30;
    private javax.swing.JLabel j31;
    private javax.swing.JLabel j32;
    private javax.swing.JLabel j33;
    private javax.swing.JLabel j34;
    private javax.swing.JLabel j35;
    private javax.swing.JLabel j36;
    private javax.swing.JLabel j37;
    private javax.swing.JLabel j38;
    private javax.swing.JLabel j39;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j40;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel record;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
